// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB6WwqMhm66y7SeHgLg1qnQz9xrwxTsKY',
    appId: '1:200932868953:web:947527f1b99d3f966d8248',
    messagingSenderId: '200932868953',
    projectId: 'test-interview-1ec73',
    authDomain: 'test-interview-1ec73.firebaseapp.com',
    storageBucket: 'test-interview-1ec73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3j8VRUWt0_gE6yVdq-MEiHQjbMRVG4qI',
    appId: '1:200932868953:android:8fea7f053c9399df6d8248',
    messagingSenderId: '200932868953',
    projectId: 'test-interview-1ec73',
    storageBucket: 'test-interview-1ec73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVaRAXVES-sdcsVmMBqe9v7593BJhhABs',
    appId: '1:200932868953:ios:204e86346f5319d56d8248',
    messagingSenderId: '200932868953',
    projectId: 'test-interview-1ec73',
    storageBucket: 'test-interview-1ec73.appspot.com',
    iosClientId: '200932868953-bt8c2bd1cs22unqp8hkdv1r6ankoqasi.apps.googleusercontent.com',
    iosBundleId: 'com.example.interview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVaRAXVES-sdcsVmMBqe9v7593BJhhABs',
    appId: '1:200932868953:ios:18e8b9f72e8d80d76d8248',
    messagingSenderId: '200932868953',
    projectId: 'test-interview-1ec73',
    storageBucket: 'test-interview-1ec73.appspot.com',
    iosClientId: '200932868953-o26ko5c940cuvh6avtj7b1cbf7g8r3km.apps.googleusercontent.com',
    iosBundleId: 'com.example.interview.RunnerTests',
  );
}
